### DISCUSSION TITLE
[BP#39] Eviter les animations Javascript / CSS coûteuses

### DISCUSSION THREAD

**Discussion by florinesueur** [cnumr/best-practices#295] [Bonnes pratiques] [answered]
Ajouter un s au http du lien ccstriggers.

Le lien est un peu daté de 2013. Je propose : [https://web.dev/animations-guide/](https://web.dev/animations-guide/)

Il est aussi possible d'ajouter une alternative : 
```css
@media (prefers-reduced-motion : no-preference ) {
  .animation {
    animation: pulse 1s linear infinite;
  }
}
```
